/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apayroll.views.main;

import com.apayroll.swing.ScrollBarCustom;

/**
 *
 * @author sly
 */
public class PayrollPanel extends javax.swing.JPanel {

    /**
     * Creates new form PayrollPanel
     */
    public PayrollPanel() {
        initComponents();
        scrollTablePane.setVerticalScrollBar(new ScrollBarCustom());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new com.apayroll.components.Card();
        scrollTablePane = new javax.swing.JScrollPane();
        payrollTable = new com.apayroll.swing.PayrollTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 249, 250));
        setMinimumSize(new java.awt.Dimension(994, 794));
        setPreferredSize(new java.awt.Dimension(994, 794));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card1.setBackground(new java.awt.Color(255, 255, 255));
        card1.setPreferredSize(new java.awt.Dimension(920, 690));
        card1.setShadowColor(new java.awt.Color(153, 153, 153));
        card1.setShadowOpacity(0.1F);
        card1.setShadowSize(15);
        card1.setShadowType(com.apayroll.components.Card.ShadowType.BOTTOM);
        card1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollTablePane.setBackground(new java.awt.Color(255, 255, 255));
        scrollTablePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        payrollTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        payrollTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empoloyee ID", "Name", "Gross Pay", "Net Pay"
            }
        ));
        scrollTablePane.setViewportView(payrollTable);

        card1.add(scrollTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 880, 600));

        jLabel2.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Payroll");
        card1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 960, 740));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.apayroll.components.Card card1;
    private javax.swing.JLabel jLabel2;
    private com.apayroll.swing.PayrollTable payrollTable;
    private javax.swing.JScrollPane scrollTablePane;
    // End of variables declaration//GEN-END:variables
}
