/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.apayroll.views.main;

/**
 *
 * @author sly
 */
public class PayrollPanel extends javax.swing.JPanel {

    /**
     * Creates new form PayrollPanel
     */
    public PayrollPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new com.apayroll.components.Card();
        jScrollPane1 = new javax.swing.JScrollPane();
        payrollTable1 = new com.apayroll.swing.PayrollTable();

        setBackground(new java.awt.Color(248, 249, 250));
        setMinimumSize(new java.awt.Dimension(994, 794));
        setPreferredSize(new java.awt.Dimension(994, 794));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card1.setBackground(new java.awt.Color(255, 255, 255));
        card1.setPreferredSize(new java.awt.Dimension(920, 690));
        card1.setShadowColor(new java.awt.Color(153, 153, 153));
        card1.setShadowOpacity(0.1F);
        card1.setShadowSize(15);
        card1.setShadowType(com.apayroll.components.Card.ShadowType.BOTTOM);
        card1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        payrollTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        payrollTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(payrollTable1);

        card1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 880, 600));

        add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 960, 740));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.apayroll.components.Card card1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.apayroll.swing.PayrollTable payrollTable1;
    // End of variables declaration//GEN-END:variables
}
