
package com.apayroll.components;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;


public class GraphicalCard extends javax.swing.JPanel {

    public GraphicalCard() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card2 = new com.apayroll.components.Card();
        jLabel1 = new javax.swing.JLabel();
        card1 = new com.apayroll.components.Card();
        sidebarItemIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(180, 156));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card2.setBackground(new java.awt.Color(255, 255, 255));
        card2.setShadowOpacity(0.1F);
        card2.setShadowSize(3);
        card2.setShadowType(com.apayroll.components.Card.ShadowType.BOTTOM);
        card2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel1.setText("CONTACT US");
        card2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        add(card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 104, 140, 40));

        card1.setBackground(new java.awt.Color(255, 255, 255));
        card1.setPreferredSize(new java.awt.Dimension(50, 50));
        card1.setShadowColor(new java.awt.Color(204, 204, 204));
        card1.setShadowOpacity(0.2F);
        card1.setShadowSize(3);
        card1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        card1.add(sidebarItemIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 20, 20));

        add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        jLabel2.setFont(new java.awt.Font("FreeSans", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Need Help?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    protected void paintComponent(Graphics gr){
        Graphics2D gr2D = (Graphics2D) gr;
        gr2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gp = new GradientPaint(0, 0, Color.decode("#38B6FF"), 0, getHeight(), Color.decode("#004AAD"));
        gr2D.setPaint(gp);
        gr2D.fillRoundRect(0,0, getWidth(), getHeight(), 15, 15);
        gr2D.setColor(new Color(255, 255, 255, 50));
        gr2D.fillOval(getWidth() - (getHeight()/2) , 10, getHeight(), getHeight());
        gr2D.fillOval(getWidth() - (getHeight()/2) - 20, getHeight()/2 + 20, getHeight(), getHeight());
        super.paintComponent(gr);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.apayroll.components.Card card1;
    private com.apayroll.components.Card card2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel sidebarItemIcon;
    // End of variables declaration//GEN-END:variables
}
